<?php

namespace FluentBooking\App\Services;


class TransStrings
{

    public static function getStrings()
    {
        return [
            'Overview'                                             => __('Overview', 'fluent-booking-pro'),
            'Start date'                                           => __('Start date', 'fluent-booking-pro'),
            'Start'                                                => __('Start', 'fluent-booking-pro'),
            'End date'                                             => __('End date', 'fluent-booking-pro'),
            'End'                                                  => __('End', 'fluent-booking-pro'),
            'Next Meetings'                                        => __('Next Meetings', 'fluent-booking-pro'),
            'Next meeting not available'                           => __('Next meeting not available', 'fluent-booking-pro'),
            'Latest Booked Meetings'                               => __('Latest Booked Meetings', 'fluent-booking-pro'),
            'No Latest Booked Event Found'                         => __('No Latest Booked Event Found', 'fluent-booking-pro'),
            'view'                                                 => __('view ', 'fluent-booking-pro'),
            'Select Date'                                          => __('Select Date', 'fluent-booking-pro'),
            'Booking Trends'                                       => __('Booking Trends', 'fluent-booking-pro'),
            'Cancel'                                               => __('Cancel', 'fluent-booking-pro'),
            'Are you sure to delete this?'                         => __('Are you sure to delete this?', 'fluent-booking-pro'),
            'Confirm'                                              => __('Confirm', 'fluent-booking-pro'),
            'General Operators'                                    => __('General Operators', 'fluent-booking-pro'),
            'Equal'                                                => __('Equal', 'fluent-booking-pro'),
            'equal'                                                => __('equal', 'fluent-booking-pro'),
            'not equal'                                            => __('not equal', 'fluent-booking-pro'),
            'Not Equal'                                            => __('Not Equal', 'fluent-booking-pro'),
            'greater than'                                         => __('greater than', 'fluent-booking-pro'),
            'Greater Than'                                         => __('Greater Than', 'fluent-booking-pro'),
            'less than'                                            => __('less than', 'fluent-booking-pro'),
            'Less Than'                                            => __('Less Than', 'fluent-booking-pro'),
            'greater than or equal'                                => __('greater than or equal', 'fluent-booking-pro'),
            'less than or equal'                                   => __('less than or equal', 'fluent-booking-pro'),
            'contains'                                             => __('contains', 'fluent-booking-pro'),
            'Contains'                                             => __('Contains', 'fluent-booking-pro'),
            'do not contains'                                      => __('do not contains', 'fluent-booking-pro'),
            'Not Contains'                                         => __('Not Contains', 'fluent-booking-pro'),
            'starts with'                                          => __('starts with', 'fluent-booking-pro'),
            'Starts With'                                          => __('Starts With', 'fluent-booking-pro'),
            'ends with'                                            => __('ends with', 'fluent-booking-pro'),
            'Ends With'                                            => __('Ends With', 'fluent-booking-pro'),
            'Advanced Operators'                                   => __('Advanced Operators', 'fluent-booking-pro'),
            'Equal to Data Length'                                 => __('Equal to Data Length', 'fluent-booking-pro'),
            'Less than to Data length'                             => __('Less than to Data length', 'fluent-booking-pro'),
            'Greater than to Data Length'                          => __('Greater than to Data Length', 'fluent-booking-pro'),
            'Regex Match'                                          => __('Regex Match', 'fluent-booking-pro'),
            'Enter length in number'                               => __('Enter length in number', 'fluent-booking-pro'),
            'Enter a value'                                        => __('Enter a value', 'fluent-booking-pro'),
            'Please enter a keyword'                               => __('Please enter a keyword', 'fluent-booking-pro'),
            'Select'                                               => __('Select', 'fluent-booking-pro'),
            'Select Condition'                                     => __('Select Condition', 'fluent-booking-pro'),
            'Match any Of'                                         => __('Match any Of', 'fluent-booking-pro'),
            'Match all of'                                         => __('Match all of', 'fluent-booking-pro'),
            'Match none of'                                        => __('Match none of', 'fluent-booking-pro'),
            'Select data source and operator first'                => __('Select data source and operator first', 'fluent-booking-pro'),
            'Match Type'                                           => __('Match Type', 'fluent-booking-pro'),
            'Delete this group'                                    => __('Delete this group', 'fluent-booking-pro'),
            'Add Another Conditional Group'                        => __('Add Another Conditional Group', 'fluent-booking-pro'),
            'Search contact'                                       => __('Search contact', 'fluent-booking-pro'),
            'Add More'                                             => __('Add More', 'fluent-booking-pro'),
            'Meeting Activities'                                   => __('Meeting Activities', 'fluent-booking-pro'),
            'No activities has been recorded for this booking'     => __('No activities has been recorded for this booking', 'fluent-booking-pro'),
            'Availability'                                         => __('Availability', 'fluent-booking-pro'),
            'Configure times when you are available for bookings.' => __('Configure times when you are available for bookings.', 'fluent-booking-pro'),
            'My Schedules'                                         => __('My Schedules', 'fluent-booking-pro'),
            'All Schedules'                                        => __('All Schedules', 'fluent-booking-pro'),
            'Add New'                                              => __('Add New', 'fluent-booking-pro'),
            'Default'                                              => __('Default', 'fluent-booking-pro'),
            'calendar events are using this schedule'              => __('calendar events are using this schedule', 'fluent-booking-pro'),
            'No events are using this schedule'                    => __('No events are using this schedule', 'fluent-booking-pro'),
            'Set as Default'                                       => __('Set as Default', 'fluent-booking-pro'),
            'Duplicate'                                            => __('Duplicate', 'fluent-booking-pro'),
            'Delete'                                               => __('Delete', 'fluent-booking-pro'),
            'No Availability found'                                => __('No Availability found', 'fluent-booking-pro'),
            'Add New Availability Schedule'                        => __('Add New Availability Schedule', 'fluent-booking-pro'),
            'Schedule Title *'                                     => __('Schedule Title *', 'fluent-booking-pro'),
            'Select Your Timezone *'                               => __('Select Your Timezone *', 'fluent-booking-pro'),
            'Default schedule'                                     => __('Default schedule', 'fluent-booking-pro'),
            'Update'                                               => __('Update', 'fluent-booking-pro'),
            'Enter Schedule Title'                                 => __('Enter Schedule Title', 'fluent-booking-pro'),
            'edit_schedule_description'                            => __('Edit the schedule below so that you can apply to your event/booking types', 'fluent-booking-pro'),
            'Timezone:'                                            => __('Timezone:', 'fluent-booking-pro'),
            'Weekly Hours'                                         => __('Weekly Hours', 'fluent-booking-pro'),
            'Add date overrides'                                   => __('Add date overrides', 'fluent-booking-pro'),
            'Unavailable'                                          => __('Unavailable', 'fluent-booking-pro'),
            'Usages List'                                          => __('Usages List', 'fluent-booking-pro'),
            'View Event'                                           => __('View Event', 'fluent-booking-pro'),
            'Select a Field'                                       => __('Select a Field', 'fluent-booking-pro'),
            'Guest Email'                                          => __('Guest Email', 'fluent-booking-pro'),
            'Back'                                                 => __('Back', 'fluent-booking-pro'),
            'Integrations'                                         => __('Integrations', 'fluent-booking-pro'),
            'Edit'                                                 => __('Edit', 'fluent-booking-pro'),
            'integrations_description'                             => __('Connect your favourite tools with your booking scheduled, completed or cancelled actions', 'fluent-booking-pro'),
            'Add New Integration'                                  => __('Add New Integration', 'fluent-booking-pro'),
            'empty_integrations_title'                             => __("You haven't added any integration feed yet. Add new integration to connect your favourite tools with your calendar", "flueng-booking-pro"),
            'Conditional Logics is a Pro Feature'                  => __('Conditional Logics is a Pro Feature', 'fluent-booking-pro'),
            'Please upgrade to pro to unlock this feature.'        => __('Please upgrade to pro to unlock this feature.', 'fluent-booking-pro'),
            'Upgrade to Pro'                                       => __('Upgrade to Pro', 'fluent-booking-pro'),
            'Interest Group is a Pro Feature'                      => __('Interest Group is a Pro Feature', 'fluent-booking-pro'),
            'This is a Pro Feature'                                => __('This is a Pro Feature', 'fluent-booking-pro'),
            'No Template found. Please make sure you are using latest version of Fluent Forms' => __('No Template found. Please make sure you are using latest version of Fluent Forms', 'fluent-booking-pro'),
            'Save Feed'                                            => __('Save Feed', 'fluent-booking-pro'),
            'General Host Settings'                                => __('General Host Settings', 'fluent-booking-pro'),
            'Manage general settings for this calendar'            => __('Manage general settings for this calendar', 'fluent-booking-pro'),
            'Recommended Image Size: 600x600. Square Orientation'  => __('Recommended Image Size: 600x600. Square Orientation', 'fluent-booking-pro'),
            'Will be shown on landing page social share meta or profile block' => __('Will be shown on landing page social share meta or profile block', 'fluent-booking-pro'),
            'Host Name / Calendar Title'                           => __('Host Name / Calendar Title', 'fluent-booking-pro'),
            'Enter Name of this calendar'                          => __('Enter Name of this calendar', 'fluent-booing-pro'),
            'Should be same as the host name'                      => __('Should be same as the host name', 'fluent-booking-pro'),
            'About'                                                => __('About', 'fluent-booking-pro'),
            'Enter description for this person / calendar'         => __('Enter description for this person / calendar', 'fluent-booking-pro'),
            'Will be shown on your calendar landing page / team block UI' => __('Will be shown on your calendar landing page / team block UI', 'fluent-booking-pro'),
            'Enable Landing Page Features for this calendar'       => __('Enable Landing Page Features for this calendar', 'fluent-booking-pro'),
            'Which Booking Forms to Show?'                         => __('Which Booking Forms to Show?', 'fluent-booking-pro'),
            'All Active Booking Forms'                             => __('All Active Booking Forms', 'fluent-booking-pro'),
            'Only Selected Active Booking Types'                   => __('Only Selected Active Booking Types', 'fluent-booking-pro'),
            'Please select which Booking Forms to show in the page?' => __('Please select which Booking Forms to show in the page?', 'fluent-booking-pro'),
            'Save Settings'                                         => __('Save Settings', 'fluent-booking-pro'),
            'enable_calendar_check_conflicts'                       => __('Enable the calendars you want to check for conflicts to prevent double bookings.', 'fluent-booking-pro'),
            'API Error:'                                            => __('API Error:', 'fluent-booking-pro'),
            'Confirm Disconnect'                                    => __('Confirm Disconnect', 'fluent-booking-pro'),
            'Remote Calendar Sync Settings'                         => __('Remote Calendar Sync Settings', 'fluent-booking-pro'),
            'set_calendars_to_check_for_conflicts'                  => __('Set the calendars to check for conflicts to prevent double bookings and add events to your remote calendar.', 'fluent-booking-pro'),
            'Add'                                                   => __('Add', 'fluent-booking-pro'),
            'Create events on'                                      => __('Create events on', 'fluent-booking-pro'),
            "Select remote calendar in where to add new events to when you're booked." => __("Select remote calendar in where to add new events to when you're booked.", "fluent-booking-pro"),
            'Select a Remote Calendar'                              => __('Select a Remote Calendar', 'fluent-booking-pro'),
            'connect_following_calendar_providers_to_sync_remote_calendar' => __('To use Remote Calendar Sync feature please connect with one of the following calendar providers', 'fluent-booking-pro'),
            'To use Remote Calendar Sync feature please configure your apps first'  => __('To use Remote Calendar Sync feature please configure your apps first', 'fluent-booking-pro'),
            'Zoom Integrations Settings'                            => __('Zoom Integrations Settings', 'fluent-booking-pro'),
            'Connect your Zoom account to create meeting when a event is booked.'   => __('Connect your Zoom account to create meeting when a event is booked.', 'fluent-booking-pro'),
            'UserZoomSettings/zoom_meeting_location_desc'           => __('Your Zoom Account is connected. Please don\'t forget to set the meeting location as "Zoom Video" if you want to create meeting in zoom.', 'fluent-booking-pro'),
            'UserZoomSettings/connect_zoom_desc'                    => __('Connect your Zoom account to create dynamic meeting in zoom for your bookings.', 'fluent-booking-pro'),
            'Connect Your Zoom Account'                             => __('Connect Your Zoom Account', 'fluent-booking-pro'),
            'Payment Settings'                                      => __('Payment Settings', 'fluent-booking-pro'),
            'Update Settings'                                       => __('Update Settings', 'fluent-booking-pro'),
            'PaymentSettings/enable_payment'
        ];

    }
}
